import { useEffect, useRef, useState, type ReactNode } from 'react';
import { NavLink, Link, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, Check, ChevronDown, ChevronRight, CircleHelp, Crown, Dices, Flame, Gift, Heart, Home, Menu, Search, ShieldCheck, Sparkles, Ticket, Trophy, UserRound, Wallet, X, Zap, CircleDot, SlidersHorizontal } from 'lucide-react';
import { games, fixtures, initialState, loadState, money, placeBets, quote, toggleSelection, type DemoState, type Fixture, type Game, type Selection } from './data';

function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const prev=document.activeElement as HTMLElement;const el=ref.current!;el.showModal();const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{el.close();document.body.style.overflow=old;prev?.focus();}},[]);
 return <dialog ref={ref} className={`modal ${wide?'wide':''}`} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===e.currentTarget)onClose();}} aria-label={title}><header><h2>{title}</h2><button className="icon-button" aria-label="Close dialog" onClick={onClose}><X/></button></header>{children}</dialog>;
}
const navItems=[{to:'/',label:'Home',icon:Home},{to:'/casino',label:'Casino',icon:Dices},{to:'/sports',label:'Sports',icon:Trophy},{to:'/bets',label:'My bets',icon:Ticket}];

export default function App(){
 const [state,setState]=useState<DemoState>(loadState);const [selections,setSelections]=useState<Selection[]>([]);const [account,setAccount]=useState(false);const [preview,setPreview]=useState<Game|null>(null);const [launched,setLaunched]=useState(false);const [searchOpen,setSearchOpen]=useState(false);const [search,setSearch]=useState('');const [slipOpen,setSlipOpen]=useState(false);const [info,setInfo]=useState<string|null>(null);const [toast,setToast]=useState('');const [storageError,setStorageError]=useState(false);const [menu,setMenu]=useState(false);const location=useLocation();const navigate=useNavigate();
 useEffect(()=>{try{localStorage.setItem('aurel-demo-v1',JSON.stringify(state));}catch{setStorageError(true);}},[state]);
 useEffect(()=>{window.scrollTo(0,0);setMenu(false);},[location.pathname]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),5000);return()=>clearTimeout(t);},[toast]);
 useEffect(()=>{const ctx=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:unknown)=>void}}).modelContext;if(!ctx)return;const life=new AbortController();try{ctx.registerTool({name:'search_aurel_games',description:'Read the fictional game catalog. Does not launch games or place bets.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof(input as {query:unknown}).query!=='string')throw new Error('query must be a string');const q=(input as {query:string}).query.toLowerCase();return games.filter(g=>`${g.name} ${g.provider}`.toLowerCase().includes(q));}},{signal:life.signal});}catch{/* Optional browser capability. */}return()=>life.abort();},[]);
 const openGame=(g:Game)=>{setLaunched(false);setPreview(g);};
 const favorite=(id:string)=>setState(s=>({...s,favorites:s.favorites.includes(id)?s.favorites.filter(x=>x!==id):[...s.favorites,id]}));
 const choose=(f:Fixture,index:number)=>{const label=index===0?f.home:index===f.odds.length-1?f.away:'Draw';setSelections(s=>toggleSelection(s,{fixtureId:f.id,match:`${f.home} vs ${f.away}`,outcome:label,odds:f.odds[index]}));};
 const place=(stake:number,mode:'single'|'accumulator')=>{const next=placeBets(state,selections,stake,mode);setState(next);setSelections([]);setToast('Demo bet placed. Follow it in My bets.');};
 const cardProps={favorite,openGame,favorites:state.favorites};
 return <><div className="demo-strip"><span>AN ORIGINAL WAY TO PLAY</span><span><span className="tiny-dot"/> Interactive demo · Virtual funds only · 18+</span></div>
 <header className="topbar"><div className="brand-area"><button className="icon-button mobile-menu" aria-label="Open menu" onClick={()=>setMenu(!menu)}><Menu/></button><Link className="brand" to="/" aria-label="Aurel home"><span className="brand-mark">A</span>AUREL<span className="brand-period">.</span></Link></div><nav className="top-nav" aria-label="Primary"><NavLink to="/casino"><Dices size={18}/> Casino</NavLink><NavLink to="/sports"><Trophy size={18}/> Sports</NavLink><button onClick={()=>{navigate('/');setTimeout(()=>document.getElementById('promotions')?.scrollIntoView({behavior:'smooth'}),50);}}>Promotions</button></nav><div className="top-actions"><button className="icon-button" aria-label="Search games and matches" onClick={()=>setSearchOpen(true)}><Search size={20}/></button><span className="header-divider"/><button className="login" onClick={()=>setAccount(true)}>Log in</button><button className="gold-button signup" onClick={()=>setAccount(true)}>Sign up <ArrowUpRight size={16}/></button></div></header>
 <div className="app-shell"><aside className={`sidebar ${menu?'menu-open':''}`}><div className="sidebar-label">DISCOVER</div><nav aria-label="Sidebar">{navItems.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end><Icon size={19}/>{label}{to==='/sports'&&<span className="live-pill">LIVE</span>}{to==='/bets'&&state.bets.length>0&&<span className="count">{state.bets.length}</span>}</NavLink>)}</nav><div className="sidebar-separator"/><div className="sidebar-label">YOUR PLAYGROUND</div><button onClick={()=>navigate('/casino?category=Live%20casino')}><CircleDot size={19}/> Live casino</button><button onClick={()=>navigate('/casino?category=Originals')}><Zap size={19}/> Originals <span className="new-label">NEW</span></button><button onClick={()=>navigate('/casino?favorites=true')}><Heart size={19}/> Favorites {state.favorites.length>0&&<span className="count">{state.favorites.length}</span>}</button><div className="sidebar-promo"><Gift size={26}/><strong>A little extra play.</strong><p>Explore the welcome offer.</p><button onClick={()=>setInfo('welcome')}>Discover more <ArrowRight size={16}/></button></div><div className="sidebar-bottom"><button onClick={()=>setInfo('responsible')}><ShieldCheck size={18}/> Responsible play</button><button onClick={()=>setInfo('help')}><CircleHelp size={18}/> Help & support</button><div className="locale">English <ChevronDown size={14}/><span>USD</span></div></div></aside>
 <main id="main-content"><Routes>
 <Route path="/" element={<><div className="page-eyebrow"><span>WELCOME TO AUREL</span><span><ShieldCheck size={14}/> Play your way.</span></div><section className="hero"><div className="hero-content"><div className="hero-kicker"><span/> THE EXTRAORDINARY AWAITS</div><h1>A different<br/>kind of <em>play.</em></h1><p>From the first spin to the final whistle.<br/>Find your moment at Aurel.</p><div className="hero-buttons"><Link className="gold-button" to="/casino">Explore casino <ArrowRight size={17}/></Link><Link className="outline-button" to="/sports">Discover sports <ArrowUpRight size={17}/></Link></div><span className="hero-note">Your playground. One destination.</span></div><div className="hero-counter"><span className="active"/><span/><span/></div><span className="hero-demo">DEMO EXPERIENCE</span></section>
 <div className="quick-links"><Link to="/casino"><span className="quick-icon"><Dices/></span><span><strong>Casino</strong><small>Discover your next favorite</small></span><ArrowUpRight/></Link><Link to="/sports"><span className="quick-icon"><Trophy/></span><span><strong>Sportsbook</strong><small>Closer to the action</small></span><ArrowUpRight/></Link><Link to="/casino?category=Live%20casino"><span className="quick-icon"><CircleDot/></span><span><strong>Live casino</strong><small>A seat at something special</small></span><ArrowUpRight/></Link></div>
 <SectionHeading icon={<Trophy/>} title="In the spotlight" subtitle="The matchday starts here." link="/sports" linkText="All sports"/><div className="match-grid">{fixtures.slice(0,3).map(f=><MatchCard key={f.id} fixture={f} selections={selections} choose={choose}/>)}</div>
 <SectionHeading icon={<Flame/>} title="Popular right now" subtitle="A new favorite is one click away." link="/casino" linkText="All games"/><div className="game-grid home-games">{games.slice(0,6).map(g=><GameCard key={g.id} game={g} {...cardProps}/>)}</div>
 <div className="lower-grid"><section className="live-feature"><div><span className="eyebrow">THE LIVE EXPERIENCE</span><h2>Your table.<br/>Your moment.</h2><p>Discover our live casino collection.</p><Link className="outline-button" to="/casino?category=Live%20casino">Take a look <ArrowUpRight size={16}/></Link></div><div className="roulette-art"/></section><section className="offer-feature" id="promotions"><Gift size={28}/><span className="eyebrow">A WARM WELCOME · DEMO OFFER</span><h2>Make your first<br/>moment golden.</h2><p>Explore a 100% welcome bonus concept.</p><button className="text-link" onClick={()=>setInfo('welcome')}>Explore the offer <ArrowRight size={16}/></button></section></div></>}/>
 <Route path="/casino" element={<Casino {...cardProps}/>}/>
 <Route path="/sports" element={<Sports selections={selections} choose={choose} slip={<BetSlip selections={selections} remove={id=>setSelections(s=>s.filter(x=>x.fixtureId!==id))} place={place} balance={state.balance}/>}/>}/>
 <Route path="/bets" element={<><PageTitle eyebrow="YOUR ACTION" title="My bets" description="Your demo bets, all in one place. Fixtures are fictional and do not settle automatically."/><div className="bets-summary"><span><Wallet size={20}/> Demo balance <strong>{money(state.balance)}</strong></span><span><Ticket size={20}/> Pending bets <strong>{state.bets.length}</strong></span></div>{!state.bets.length?<Empty title="Your next match is waiting." text="Explore the sportsbook and place your first bet using virtual funds." action={<Link className="gold-button" to="/sports">Explore sports <ArrowRight size={16}/></Link>}/>:<div className="bet-history">{state.bets.map(b=><article className="history-card" key={b.id}><div><span className="eyebrow">{b.mode==='single'?'SINGLE':'ACCUMULATOR'} · DEMO</span><span className="pending">Pending</span></div>{b.selections.map(s=><div className="history-selection" key={s.fixtureId}><strong>{s.outcome} <span>{s.odds.toFixed(2)}</span></strong><small>{s.match}</small></div>)}<div className="history-totals"><span>Stake <b>{money(b.stake)}</b></span><span>Potential return <b>{money(b.potential)}</b></span></div><small className="muted">{new Date(b.createdAt).toLocaleString()}</small></article>)}</div>}</>}/>
 <Route path="*" element={<Empty title="This page is out of play." text="Return to the lobby to find casino games and sports." action={<Link className="gold-button" to="/">Back home</Link>}/>}/>
 </Routes><footer><div className="footer-top"><Link className="brand small-brand" to="/">AUREL<span className="brand-period">.</span></Link><span>A different kind of play.</span><button onClick={()=>setInfo('responsible')}>Play responsibly <ShieldCheck size={16}/></button></div><div className="footer-bottom"><span className="age">18+</span><p>For adults only. Interactive prototype with fictional games, scores, odds and offers. All balances are virtual USD. No real money, deposits or prizes.</p><span>© {new Date().getFullYear()} Aurel concept</span></div>{storageError&&<p role="status">Browser storage is unavailable. Your demo will reset when you reload.</p>}</footer></main></div>
 <nav className="mobile-nav" aria-label="Mobile">{navItems.map(({to,label,icon:Icon})=><NavLink key={to} to={to} end><Icon size={21}/><span>{label==='My bets'?'Bets':label}</span></NavLink>)}<button onClick={()=>setAccount(true)}><UserRound size={21}/><span>Account</span></button></nav>
 {selections.length>0&&<button className={`floating-slip ${location.pathname==='/sports'?'sports-slip':''}`} onClick={()=>setSlipOpen(true)}><Ticket size={19}/> Bet slip <span>{selections.length}</span><ChevronRight size={18}/></button>}
 {toast&&<div className="toast" role="status"><Check size={18}/>{toast}<button aria-label="Dismiss notification" onClick={()=>setToast('')}><X size={16}/></button></div>}
 {account&&<Modal title="Your demo account" onClose={()=>setAccount(false)}><div className="account-wallet"><Wallet size={30}/><span>VIRTUAL USD BALANCE</span><strong>{money(state.balance)}</strong></div><p>This prototype is ready to explore. No registration or personal details are needed, and no real money is used.</p><button className="gold-button full" onClick={()=>{setAccount(false);navigate('/sports');}}>Start exploring <ArrowRight size={17}/></button><button className="outline-button full" onClick={()=>{setState({...initialState});setSelections([]);setToast('Demo reset: $1,000 virtual balance restored.');}}>Reset demo account</button><small className="muted">Reset restores $1,000 and clears your demo bets and favorites.</small></Modal>}
 {preview&&<Modal title={preview.name} onClose={()=>setPreview(null)}><div className={`preview-art tile-${preview.tile}`} role="img" aria-label={`${preview.name} artwork`}/><p className="eyebrow">{preview.provider} · {preview.category} · DEMO</p>{launched?<div className="launch-message" role="status"><Check/><h3>You’re in preview mode.</h3><p>This is a simulated game launch. No game provider is connected and no wager has been placed.</p></div>:<><p>Take a closer look at {preview.name}. This fictional game is part of the Aurel design concept.</p><button className="gold-button full" onClick={()=>setLaunched(true)}>Launch demo preview <ArrowRight size={17}/></button></>}</Modal>}
 {searchOpen&&<Modal title="Find your next moment" onClose={()=>setSearchOpen(false)} wide><label className="search-field"><Search size={19}/><input autoFocus placeholder="Search games, teams or leagues" value={search} onChange={e=>setSearch(e.target.value)}/></label><div className="search-results"><h3>Games</h3>{games.filter(g=>`${g.name} ${g.provider}`.toLowerCase().includes(search.toLowerCase())).map(g=><button key={g.id} onClick={()=>{setSearchOpen(false);openGame(g);}}><Dices size={18}/><span>{g.name}<small>{g.provider}</small></span><ArrowUpRight size={17}/></button>)}{!games.some(g=>`${g.name} ${g.provider}`.toLowerCase().includes(search.toLowerCase()))&&<p className="muted">No games found. Try another name.</p>}<h3>Matches</h3>{fixtures.filter(f=>`${f.home} ${f.away} ${f.league}`.toLowerCase().includes(search.toLowerCase())).map(f=><button key={f.id} onClick={()=>{setSearchOpen(false);navigate(`/sports?sport=${f.sport}&tab=${f.live?'Live':'Upcoming'}&query=${encodeURIComponent(f.home)}`);}}><Trophy size={18}/><span>{f.home} vs {f.away}<small>{f.league} · Demo fixture</small></span><ArrowUpRight size={17}/></button>)}{!fixtures.some(f=>`${f.home} ${f.away} ${f.league}`.toLowerCase().includes(search.toLowerCase()))&&<p className="muted">No matches found. Try another team or league.</p>}</div></Modal>}
 {slipOpen&&<Modal title="Your bet slip" onClose={()=>setSlipOpen(false)}><BetSlip selections={selections} remove={id=>setSelections(s=>s.filter(x=>x.fixtureId!==id))} balance={state.balance} place={place}/></Modal>}
 {info&&<Modal title={info==='welcome'?'A golden welcome':info==='help'?'Help & support':'Keep play in perspective'} onClose={()=>setInfo(null)}>{info==='welcome'?<><Gift size={42} className="gold"/><h3>100% welcome bonus concept</h3><p>This is a fictional promotional offer for design review. No bonus can be claimed, and no deposit is available.</p><p>Actual offer eligibility, limits and terms would be supplied by the operator before a production launch.</p><button className="gold-button full" onClick={()=>{setInfo(null);navigate('/casino');}}>Explore demo games</button></>:info==='help'?<><p>Use Casino to browse and favorite games. Use Sports to select demo odds, enter a virtual stake, and place a simulated bet.</p><p>Your bets and balance are saved in this browser. Reset them from the demo account dialog.</p><p>This prototype has no live support or financial transactions.</p></>:<><ShieldCheck size={40} className="gold"/><h3>Play for entertainment.</h3><p>Adults only, 18+. Take regular breaks and set boundaries on time and spending. Never chase losses or treat gambling as income.</p><p>This prototype uses virtual funds only. If gambling is causing concern, seek help from a trusted person or a support service in your country.</p></>}</Modal>}
 </>;
}

function PageTitle({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <div className="page-title"><span className="eyebrow">{eyebrow}</span><h1>{title}<span>.</span></h1><p>{description}</p></div>}
function SectionHeading({icon,title,subtitle,link,linkText}:{icon:ReactNode;title:string;subtitle:string;link:string;linkText:string}){return <div className="section-heading"><div><h2>{icon}{title}</h2><p>{subtitle}</p></div><Link to={link}>{linkText}<ChevronRight size={16}/></Link></div>}
function Empty({title,text,action}:{title:string;text:string;action?:ReactNode}){return <div className="empty"><Search size={32}/><h2>{title}</h2><p>{text}</p>{action}</div>}
function GameCard({game:g,favorites,favorite,openGame}:{game:Game;favorites:string[];favorite:(id:string)=>void;openGame:(g:Game)=>void}){return <article className="game-card"><button className={`game-art tile-${g.tile}`} aria-label={`Preview ${g.name}`} onClick={()=>openGame(g)}><span className="game-shade"/>{g.tag&&<span className={`game-tag tag-${g.tag.toLowerCase()}`}>{g.tag==='HOT'&&<Flame size={11}/>} {g.tag}</span>}<span className="game-art-title">{g.name}</span><span className="play-overlay">Explore <ArrowUpRight size={19}/></span></button><button className={`favorite ${favorites.includes(g.id)?'is-favorite':''}`} aria-label={`${favorites.includes(g.id)?'Remove':'Add'} ${g.name} ${favorites.includes(g.id)?'from':'to'} favorites`} aria-pressed={favorites.includes(g.id)} onClick={()=>favorite(g.id)}><Heart size={15} fill={favorites.includes(g.id)?'currentColor':'none'}/></button><div className="game-meta"><h3>{g.name}</h3><span>{g.provider}</span></div></article>}
function MatchCard({fixture:f,selections,choose}:{fixture:Fixture;selections:Selection[];choose:(f:Fixture,i:number)=>void}){return <article className="match-card"><div className="match-top"><span><Trophy size={12}/>{f.league}</span><span className={f.live?'live-text':'muted'}>{f.live&&<span className="tiny-dot"/>}{f.live?'LIVE':'UPCOMING'}</span></div><div className="teams"><div><span className={`team-badge badge-${f.id}`}>{f.homeCode.slice(0,1)}</span><span>{f.home}</span></div><div className="score"><strong>{f.score||'VS'}</strong><small>{f.time}</small></div><div><span className={`team-badge away badge-${f.id}`}>{f.awayCode.slice(0,1)}</span><span>{f.away}</span></div></div><div className="odds-row">{f.odds.map((o,i)=>{const outcome=i===0?f.home:i===f.odds.length-1?f.away:'Draw';const selected=selections.some(s=>s.fixtureId===f.id&&s.outcome===outcome);return <button key={i} className={selected?'selected':''} aria-label={`${f.home} versus ${f.away}: ${outcome} at ${o.toFixed(2)}`} aria-pressed={selected} onClick={()=>choose(f,i)}><span>{i===0?'1':i===f.odds.length-1?'2':'X'}</span><strong>{o.toFixed(2)}</strong></button>;})}</div><span className="match-demo">Fictional fixture · Demo odds</span></article>}
function Casino(props:{favorites:string[];favorite:(id:string)=>void;openGame:(g:Game)=>void}){const location=useLocation();const params=new URLSearchParams(location.search);const [category,setCategory]=useState(params.get('category')||'All games');const [onlyFavorites,setOnlyFavorites]=useState(params.get('favorites')==='true');const [provider,setProvider]=useState('All providers');const [query,setQuery]=useState('');useEffect(()=>{setCategory(new URLSearchParams(location.search).get('category')||'All games');setOnlyFavorites(new URLSearchParams(location.search).get('favorites')==='true');},[location.search]);const visible=games.filter(g=>(category==='All games'||g.category===category)&&(provider==='All providers'||g.provider===provider)&&(!onlyFavorites||props.favorites.includes(g.id))&&g.name.toLowerCase().includes(query.toLowerCase()));return <><PageTitle eyebrow="FIND YOUR FAVORITE" title="The casino" description="Extraordinary worlds. Endless possibilities. Explore our fictional game collection."/><div className="casino-banner"><Sparkles/><div><h2>A world beyond the ordinary.</h2><p>Original games. Unmistakably Aurel.</p></div><span>DEMO COLLECTION</span></div><div className="filter-bar"><label className="search-field"><Search size={18}/><input aria-label="Search casino games" placeholder="Search games" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="select-wrap"><SlidersHorizontal size={16}/><select aria-label="Game provider" value={provider} onChange={e=>setProvider(e.target.value)}>{['All providers','Aurel Studios','Orbit Games','Ember Play'].map(p=><option key={p}>{p}</option>)}</select></label></div><div className="tabs">{['All games','Slots','Live casino','Originals'].map(c=><button key={c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}</button>)}<button className={onlyFavorites?'active':''} aria-pressed={onlyFavorites} onClick={()=>setOnlyFavorites(!onlyFavorites)}><Heart size={16}/> Favorites</button></div><div className="results-label">{visible.length} games <span>Fictional titles · Demo previews</span></div>{visible.length?<div className="game-grid catalog">{visible.map(g=><GameCard key={g.id} game={g} {...props}/>)}</div>:<Empty title="No games in this corner yet." text="Try another search or reset your filters." action={<button className="outline-button" onClick={()=>{setQuery('');setCategory('All games');setProvider('All providers');setOnlyFavorites(false);}}>Reset filters</button>}/>}</>}
function Sports({selections,choose,slip}:{selections:Selection[];choose:(f:Fixture,i:number)=>void;slip:ReactNode}){const loc=useLocation();const p=new URLSearchParams(loc.search);const [sport,setSport]=useState(p.get('sport')||'Football');const [tab,setTab]=useState(p.get('tab')||'Live');const [league,setLeague]=useState('All leagues');const [query,setQuery]=useState(p.get('query')||'');useEffect(()=>{const p=new URLSearchParams(loc.search);setSport(p.get('sport')||'Football');setTab(p.get('tab')||'Live');setQuery(p.get('query')||'');setLeague('All leagues');},[loc.search]);const visible=fixtures.filter(f=>f.sport===sport&&f.live===(tab==='Live')&&(league==='All leagues'||f.league===league)&&`${f.home} ${f.away}`.toLowerCase().includes(query.toLowerCase()));return <><PageTitle eyebrow="EVERY MOMENT MATTERS" title="The sportsbook" description="Get closer to the game. Explore fictional fixtures with virtual funds."/><div className="sport-picker">{['Football','Basketball','Tennis'].map((s,i)=><button className={sport===s?'active':''} key={s} onClick={()=>{setSport(s);setLeague('All leagues');setQuery('');}}><span>{['⚽','🏀','🎾'][i]}</span>{s}</button>)}</div><div className="sports-layout"><div><div className="sports-toolbar"><div className="tabs"><button className={tab==='Live'?'active':''} onClick={()=>setTab('Live')}><span className="tiny-dot"/> Live</button><button className={tab==='Upcoming'?'active':''} onClick={()=>setTab('Upcoming')}>Upcoming</button></div><select aria-label="League" value={league} onChange={e=>setLeague(e.target.value)}><option>All leagues</option>{[...new Set(fixtures.filter(f=>f.sport===sport).map(f=>f.league))].map(l=><option key={l}>{l}</option>)}</select></div><label className="search-field sports-search"><Search size={18}/><input aria-label="Search teams" placeholder="Search teams" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="sports-matches">{visible.map(f=><MatchCard key={f.id} fixture={f} selections={selections} choose={choose}/>)}</div>{!visible.length&&<Empty title="No matches found." text="Try Upcoming, another sport, or clear your filters." action={<button className="outline-button" onClick={()=>{setQuery('');setLeague('All leagues');setTab(tab==='Live'?'Upcoming':'Live');}}>Show {tab==='Live'?'upcoming':'live'} matches</button>}/>}</div><aside className="desktop-slip">{slip}</aside></div></>}
function BetSlip({selections,remove,place,balance}:{selections:Selection[];remove:(id:string)=>void;place:(stake:number,mode:'single'|'accumulator')=>void;balance:number}){const [mode,setMode]=useState<'single'|'accumulator'>('single');const [stake,setStake]=useState('10');const [error,setError]=useState('');const totals=quote(selections,Number(stake),mode);return <section className="bet-slip"><div className="slip-heading"><h2><Ticket size={20}/> Bet slip</h2><span>{selections.length}</span></div>{!selections.length?<div className="slip-empty"><Ticket size={34}/><h3>Your next move.</h3><p>Select odds on a match to start your demo bet.</p><span>Virtual funds. Real possibilities.</span></div>:<><div className="tabs"><button className={mode==='single'?'active':''} onClick={()=>{setMode('single');setError('');}}>Singles</button><button className={mode==='accumulator'?'active':''} onClick={()=>{setMode('accumulator');setError('');}}>Accumulator</button></div>{selections.map(s=><div className="slip-selection" key={s.fixtureId}><button className="icon-button" aria-label={`Remove ${s.outcome}`} onClick={()=>remove(s.fixtureId)}><X size={15}/></button><strong>{s.outcome}<span>{s.odds.toFixed(2)}</span></strong><small>{s.match}</small><span className="muted">Match winner · Demo</span></div>)}<label className="stake-label">{mode==='single'?'Stake per selection':'Total stake'}<div className="stake-input"><span>USD</span><input aria-label="Stake" type="number" min="0.01" step="0.01" value={stake} onChange={e=>{setStake(e.target.value);setError('');}}/></div></label><div className="stake-presets">{[10,25,50,100].map(n=><button key={n} onClick={()=>{setStake(String(n));setError('');}}>${n}</button>)}</div><div className="slip-total"><span>Total stake</span><strong>{money(Number.isFinite(totals.cost)?totals.cost:0)}</strong></div><div className="slip-total potential"><span>Potential return</span><strong>{money(Number.isFinite(totals.potential)?totals.potential:0)}</strong></div>{error&&<p className="form-error" role="alert">{error}</p>}<button className="gold-button full" onClick={()=>{try{place(Number(stake),mode);setError('');}catch(e){setError((e as Error).message);}}}>Place demo bet <ArrowRight size={16}/></button><small className="muted">Demo balance: {money(balance)}</small></>}<div className="slip-disclaimer"><ShieldCheck size={15}/> Virtual funds only · No real wagering</div></section>}
