import { useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { ArrowRight, Search, Ticket, Wallet } from 'lucide-react';
import { money, type BetStatus, type DemoBet } from './data';
import './my-bets.css';

type Props={bets:DemoBet[];balance:number;settle:(id:string,status:Exclude<BetStatus,'Pending'>)=>void};
type Filter='Open'|'Settled'|'Won'|'Lost'|'Void';
const filters:Filter[]=['Open','Settled','Won','Lost','Void'];
function matches(b:DemoBet,filter:Filter){return filter==='Open'?b.status==='Pending':filter==='Settled'?b.status!=='Pending':b.status===filter}
function BetCard({bet:b}:{bet:DemoBet}){return <article className="history-card"><div><span className="eyebrow">{b.mode==='single'?'SINGLE':'ACCUMULATOR'} · DEMO</span><span className="pending">{b.status}</span></div>{b.selections.map((s,i)=><div className="history-selection" key={`${s.fixtureId}-${i}`}><strong>{s.outcome} <span>{s.odds.toFixed(2)}</span></strong><small>{s.match} · {s.market||'Match winner'}</small></div>)}<div className="history-totals"><span>Stake <b>{money(b.stake*(b.mode==='single'?b.selections.length:1))}</b></span><span>{b.status==='Pending'?'Potential return':'Actual return'} <b>{money(b.status==='Pending'?b.potential:(b.actualReturn||0))}</b></span></div><small className="muted">{new Date(b.createdAt).toLocaleString()}</small><Link className="bet-details-link" to={`/bets/${encodeURIComponent(b.id)}`}>Bet details <ArrowRight size={15}/></Link></article>}
export function MyBets({bets,balance}:Props){const [filter,setFilter]=useState<Filter>('Open');const visible=bets.filter(b=>matches(b,filter));return <><div className="page-title"><span className="eyebrow">YOUR ACTION</span><h1>My bets<span>.</span></h1><p>Your fictional demo bets and results. Bets do not settle automatically.</p></div><div className="bets-summary"><span><Wallet size={20}/> Demo balance <strong>{money(balance)}</strong></span><span><Ticket size={20}/> Open bets <strong>{bets.filter(b=>b.status==='Pending').length}</strong></span></div><div className="tabs my-bets-tabs" role="group" aria-label="Bet status">{filters.map(f=><button key={f} className={filter===f?'active':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f}</button>)}</div>{visible.length?<div className="bet-history">{visible.map(b=><BetCard bet={b} key={b.id}/>)}</div>:<div className="empty"><Search size={32}/><h2>No {filter.toLowerCase()} bets.</h2><p>{filter==='Open'?'Explore the sportsbook and place your first bet using virtual funds.':'Demo bets in this status will appear here.'}</p><Link className="gold-button" to="/sports">Explore sports <ArrowRight size={16}/></Link></div>}</>}
export function BetDetails({bets,settle}:Props){const {betId}=useParams();const bet=bets.find(b=>b.id===betId);if(!bet)return <div className="empty"><Ticket size={30}/><h2>Bet unavailable.</h2><p>This demo bet could not be found.</p><Link className="gold-button" to="/bets">My bets</Link></div>;return <div className="bet-detail-page"><Link className="bet-details-link" to="/bets">← My bets</Link><div className="page-title"><span className="eyebrow">DEMO BET</span><h1>Bet details<span>.</span></h1><p>Placed {new Date(bet.createdAt).toLocaleString()} · {bet.status}</p></div><div className="bet-history"><BetCard bet={bet}/></div><section className="bet-detail-summary"><h2>Summary</h2><dl><div><dt>Bet type</dt><dd>{bet.mode==='single'?'Single':'Accumulator'}</dd></div><div><dt>Selections</dt><dd>{bet.selections.length}</dd></div><div><dt>Total stake</dt><dd>{money(bet.stake*(bet.mode==='single'?bet.selections.length:1))}</dd></div><div><dt>Potential return</dt><dd>{money(bet.potential)}</dd></div>{bet.status!=='Pending'&&<div><dt>Actual return</dt><dd>{money(bet.actualReturn||0)}</dd></div>}{bet.settledAt&&<div><dt>Settled</dt><dd>{new Date(bet.settledAt).toLocaleString()}</dd></div>}</dl>{bet.status==='Pending'&&<div className="demo-settlement"><p>Demo review controls only. Choose a simulated result to preview settled states.</p><button onClick={()=>settle(bet.id,'Won')}>Mark won</button><button onClick={()=>settle(bet.id,'Lost')}>Mark lost</button><button onClick={()=>settle(bet.id,'Void')}>Mark void</button></div>}</section></div>}
