import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowDownLeft, ArrowRight, ArrowUpRight, Check, Heart, LogOut, Rocket, ShieldCheck, Wallet } from 'lucide-react';
import { money, type Game } from './data';

export const crashGames: Game[] = [
  {id:'crash-ignition',name:'Ignition',provider:'UNO Studios',category:'Crash',tile:0,image:'/uno-tile-crash.webp',tag:'NEW'},
  {id:'crash-orbit',name:'Orbit Rush',provider:'UNO Studios',category:'Crash',tile:1,image:'/uno-tile-crash.webp'},
  {id:'crash-neon',name:'Neon Velocity',provider:'Orbit Games',category:'Crash',tile:2,image:'/uno-tile-crash.webp'},
  {id:'crash-solar',name:'Solar Flight',provider:'Ember Play',category:'Crash',tile:3,image:'/uno-tile-crash.webp'},
];

export function CrashCollection({favorites,favorite,openGame,compact=false}:{favorites:string[];favorite:(id:string)=>void;openGame:(g:Game)=>void;compact?:boolean}){
  const [query,setQuery]=useState('');
  const visible=crashGames.filter(g=>g.name.toLowerCase().includes(query.toLowerCase()));
  return <>
    {!compact&&<><div className="crash-banner"><div><span className="eyebrow">THE NEXT CHAPTER OF PLAY</span><h1>Lift off.<br/><em>Explore Crash.</em></h1><p>Four fictional worlds. One new way to explore UNO.</p><span className="crash-demo"><ShieldCheck size={15}/> Demo previews · No real wagering</span></div><img src="/uno-tile-crash.webp" alt="Gold and coral rocket" width="640" height="640"/></div><label className="search-field crash-search"><Rocket size={19}/><input aria-label="Search crash games" placeholder="Search Crash Games" value={query} onChange={e=>setQuery(e.target.value)}/></label></>}
    <div className="crash-grid">{visible.map(g=><article className={`crash-card crash-color-${g.tile}`} key={g.id}><button className="crash-preview" onClick={()=>openGame(g)} aria-label={`Preview ${g.name}`}><span className="crash-card-tag">{g.tag||'DEMO'}</span><img src={g.image} alt="" width="640" height="640" loading="lazy"/><div><span>{g.provider}</span><h3>{g.name}</h3><span className="crash-play">Explore game <ArrowUpRight size={17}/></span></div></button><button className="favorite" aria-label={`${favorites.includes(g.id)?'Remove':'Add'} ${g.name} ${favorites.includes(g.id)?'from':'to'} favorites`} aria-pressed={favorites.includes(g.id)} onClick={()=>favorite(g.id)}><Heart size={16} fill={favorites.includes(g.id)?'currentColor':'none'}/></button></article>)}</div>
    {!visible.length&&<div className="empty"><Rocket/><h2>No Crash Games found.</h2><p>Try another game name.</p><button className="outline-button" onClick={()=>setQuery('')}>Clear search</button></div>}
  </>;
}

export function DemoAccount({name,loggedIn,balance,onLogin,onLogout,onDeposit,onReset,onProfileMenu}:{name:string;loggedIn:boolean;balance:number;onLogin:()=>void;onLogout:()=>void;onDeposit:()=>void;onReset:()=>void;onProfileMenu:()=>void}){
  return loggedIn?<><div className="account-identity"><button className="avatar" aria-label="Open account menu" aria-haspopup="menu" onClick={onProfileMenu}>{name.trim().charAt(0).toUpperCase()||'U'}</button><div><h3>{name}</h3><span>Demo account · This browser</span></div><span className="account-status">DEMO</span></div><div className="crypto-wallet"><div><Wallet size={20}/><span>Total demo balance</span></div><strong>{money(balance)}</strong><span>USD · Virtual funds</span><div className="wallet-asset"><span className="coin-icon">₮</span><span>Demo USD wallet<small>Crypto-style interface preview</small></span><Check size={18}/></div></div><button className="gold-button full" onClick={onDeposit}><ArrowDownLeft size={18}/> Deposit</button><p className="wallet-note">No real cryptocurrency, wallet address or payment is connected.</p><div className="account-options"><Link to="/bets"><Wallet size={17}/> View demo bets <ArrowUpRight size={16}/></Link><button onClick={onReset}>Reset demo account <ArrowRight size={16}/></button><button onClick={onLogout}><LogOut size={17}/> Log out</button></div><small className="muted">Reset restores $1,000 and clears your demo bets and favorites.</small></>:<div className="demo-login"><div className="login-emblem"><Wallet size={34}/></div><span className="eyebrow">WELCOME TO UNO</span><h3>Your play.<br/>All in one place.</h3><p>Preview your personal wallet, favorites and bets with $1,000 in virtual funds.</p><button className="gold-button full" onClick={onLogin}>Enter demo account <ArrowRight size={18}/></button><small>No password or personal details needed. This is a simulated login saved in this browser.</small></div>;
}

export function DemoDeposit({balance,onDeposit}:{balance:number;onDeposit:(amount:number)=>void}){
  const [amount,setAmount]=useState('100');const [error,setError]=useState('');const [success,setSuccess]=useState<number|null>(null);
  return <div className="deposit-panel"><div className="deposit-asset"><span className="coin-icon">₮</span><div><strong>Demo USD</strong><span>Virtual wallet · No blockchain transfer</span></div><span className="offer-demo">DEMO</span></div><div className="deposit-balance"><span>Available balance</span><strong>{money(balance)}</strong></div><form onSubmit={e=>{e.preventDefault();try{const value=Number(amount);onDeposit(value);setError('');setSuccess(value);}catch(e){setError((e as Error).message);setSuccess(null);}}} noValidate><label className="stake-label">Amount to add<div className="stake-input"><span>USD</span><input autoFocus aria-label="Demo deposit amount" type="number" min="1" max="10000" step="0.01" value={amount} onChange={e=>{setAmount(e.target.value);setError('');setSuccess(null);}}/></div></label><div className="stake-presets">{[100,250,500,1000].map(v=><button key={v} type="button" onClick={()=>{setAmount(String(v));setError('');setSuccess(null);}}>${v}</button>)}</div>{error&&<p className="form-error" role="alert">{error}</p>}{success!==null&&<p className="deposit-success" role="status"><Check size={18}/>{money(success)} added to your demo wallet.</p>}<button className="gold-button full" type="submit"><ArrowDownLeft size={18}/> Add demo funds</button></form><p className="wallet-note"><ShieldCheck size={17}/> For preview only. No money is charged and no cryptocurrency is transferred. Add $1–$10,000 per demo deposit.</p></div>;
}
